name: Publish package to Bazel registry
on:
  push:
    tags:
      - "v*"

jobs:
  publish-package:
    runs-on: ubuntu
    steps:
      - name: Write private key
        run: echo "${{ secrets.BAZEL_REGISTRY_DEPLOY_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519

      - uses: actions/checkout@v1
        with:
          repository: ssh://git@${{ secrets.INSTANCE_SSH_HOST }}/460nm/bazel-registry
          ref: main

      - uses: ./actions/publish_forgejo_module
        with:
          module_name: rules_slang
          version: ${FORGEJO_REF_NAME:1}

      - uses: actions/send-pr@v1
        with:
          topic: release_rules_slang_${{ forge.ref_name }}
